package handler

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"net/http"
	netmail "net/mail"
	neturl "net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/Jeffreasy/JeffriesBackend/internal/model"
	"github.com/Jeffreasy/JeffriesBackend/internal/store"
)

var intakeKeyPattern = regexp.MustCompile(`^[A-Za-z0-9._:-]+$`)

type PublicIntakeHandler struct {
	store  *store.LaventeCareStore
	userID string
}

func NewPublicIntakeHandler(intakeStore *store.LaventeCareStore, userID string) *PublicIntakeHandler {
	return &PublicIntakeHandler{store: intakeStore, userID: userID}
}

// Submit accepts the scoped server-to-server public contact intake. CRM writes
// finish before 201 is returned; retries with the same key return the first IDs.
func (h *PublicIntakeHandler) Submit(w http.ResponseWriter, r *http.Request) {
	key := strings.TrimSpace(r.Header.Get("Idempotency-Key"))
	if !validIntakeKey(key) {
		Error(w, http.StatusBadRequest, "Idempotency-Key is verplicht (8-128 veilige tekens).")
		return
	}

	var input model.LCPublicIntakeRequest
	if err := DecodeJSON(r, &input); err != nil {
		RespondDecodeError(w, err)
		return
	}
	if err := normalizePublicIntake(&input); err != nil {
		Error(w, http.StatusBadRequest, err.Error())
		return
	}
	if input.RequestID != key {
		Error(w, http.StatusBadRequest, "requestId moet gelijk zijn aan Idempotency-Key.")
		return
	}

	payloadHash, err := publicIntakePayloadHash(input)
	if err != nil {
		InternalError(w, r, err)
		return
	}
	result, err := h.store.ProcessPublicIntake(r.Context(), h.userID, key, payloadHash, input)
	if err != nil {
		switch {
		case errors.Is(err, store.ErrIntakeIdempotencyConflict):
			Error(w, http.StatusConflict, "Idempotency-Key is al gebruikt voor een andere aanvraag.")
		case errors.Is(err, store.ErrIntakeStillProcessing):
			w.Header().Set("Retry-After", "2")
			Error(w, http.StatusServiceUnavailable, "Aanvraag wordt nog verwerkt; probeer dezelfde key opnieuw.")
		default:
			InternalError(w, r, err)
		}
		return
	}
	status := http.StatusCreated
	if result.Duplicate {
		status = http.StatusOK
	}
	JSON(w, status, result)
}

// publicIntakePayloadHash intentionally excludes SubmittedAt: it is transport
// metadata generated by the website for each delivery attempt, not a business
// field. A retry with the same request ID must therefore replay the original
// response instead of conflicting solely because its timestamp changed.
func publicIntakePayloadHash(input model.LCPublicIntakeRequest) (string, error) {
	input.SubmittedAt = ""
	canonical, err := json.Marshal(input)
	if err != nil {
		return "", err
	}
	sum := sha256.Sum256(canonical)
	return hex.EncodeToString(sum[:]), nil
}

func normalizeOptionalHTTPURL(field, raw string, originOnly bool) (string, error) {
	if raw == "" {
		return "", nil
	}
	parsed, err := neturl.ParseRequestURI(raw)
	if err != nil || parsed.Host == "" || parsed.Hostname() == "" || parsed.User != nil ||
		(parsed.Scheme != "http" && parsed.Scheme != "https") {
		return "", errors.New(field + " moet een absolute http- of https-URL zijn")
	}
	if originOnly && (parsed.Path != "" || parsed.RawQuery != "" || parsed.Fragment != "") {
		return "", errors.New("origin mag alleen schema en host bevatten")
	}
	parsed.Scheme = strings.ToLower(parsed.Scheme)
	parsed.Host = strings.ToLower(parsed.Host)
	return parsed.String(), nil
}

func validIntakeKey(key string) bool {
	return len(key) >= 8 && len(key) <= 128 && intakeKeyPattern.MatchString(key)
}

func normalizePublicIntake(input *model.LCPublicIntakeRequest) error {
	input.RequestID = strings.TrimSpace(input.RequestID)
	input.Source = strings.TrimSpace(input.Source)
	if input.Source == "" {
		input.Source = "laventecare.nl"
	}
	input.Name = strings.TrimSpace(input.Name)
	input.Email = strings.ToLower(strings.TrimSpace(input.Email))
	input.Phone = strings.TrimSpace(input.Phone)
	input.CompanyName = strings.TrimSpace(input.CompanyName)
	input.Website = strings.TrimSpace(input.Website)
	input.ProjectType = strings.TrimSpace(input.ProjectType)
	input.Budget = strings.TrimSpace(input.Budget)
	input.Timeline = strings.TrimSpace(input.Timeline)
	input.Goal = strings.TrimSpace(input.Goal)
	input.Message = strings.TrimSpace(input.Message)
	input.PageURL = strings.TrimSpace(input.PageURL)
	input.Origin = strings.TrimSpace(input.Origin)
	input.SubmittedAt = strings.TrimSpace(input.SubmittedAt)

	var err error
	if input.Website, err = normalizeOptionalHTTPURL("website", input.Website, false); err != nil {
		return err
	}
	if input.PageURL, err = normalizeOptionalHTTPURL("pageUrl", input.PageURL, false); err != nil {
		return err
	}
	if input.Origin, err = normalizeOptionalHTTPURL("origin", input.Origin, true); err != nil {
		return err
	}
	if input.SubmittedAt != "" {
		submittedAt, parseErr := time.Parse(time.RFC3339, input.SubmittedAt)
		if parseErr != nil {
			return errors.New("submittedAt moet een geldige RFC3339-datum zijn")
		}
		input.SubmittedAt = submittedAt.UTC().Format(time.RFC3339Nano)
	}

	if input.Name == "" {
		return errors.New("name is verplicht")
	}
	if input.Email == "" {
		return errors.New("email is verplicht")
	}
	address, err := netmail.ParseAddress(input.Email)
	if err != nil || !strings.EqualFold(address.Address, input.Email) {
		return errors.New("email is ongeldig")
	}
	input.Email = strings.ToLower(address.Address)
	limits := []struct {
		name  string
		value string
		max   int
	}{
		{"requestId", input.RequestID, 128}, {"source", input.Source, 100},
		{"name", input.Name, 200}, {"email", input.Email, 320}, {"phone", input.Phone, 80},
		{"companyName", input.CompanyName, 250}, {"website", input.Website, 2048},
		{"projectType", input.ProjectType, 200}, {"budget", input.Budget, 100},
		{"timeline", input.Timeline, 200}, {"goal", input.Goal, 8000},
		{"message", input.Message, 8000}, {"pageUrl", input.PageURL, 2048},
		{"origin", input.Origin, 2048}, {"submittedAt", input.SubmittedAt, 64},
	}
	for _, field := range limits {
		if utf8.RuneCountInString(field.value) > field.max {
			return errors.New(field.name + " is te lang")
		}
	}
	return nil
}
