"""add_mac_address_to_devices

Revision ID: 2b0e59734abe
Revises: 10c16305593b
Create Date: 2026-03-17 15:13:07.132870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b0e59734abe'
down_revision: Union[str, None] = '10c16305593b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('mac_address', sa.String(length=17), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'mac_address')
    # ### end Alembic commands ###
