"""device_event_uuid_pk_add_pagination_indexes

Revision ID: 10c16305593b
Revises: b9fad77027de
Create Date: 2026-03-14 21:49:17.777638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10c16305593b'
down_revision: Union[str, None] = 'b9fad77027de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_events', sa.Column('id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_device_events_device_id'), 'device_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_events_time'), 'device_events', ['time'], unique=False)
    op.create_index(op.f('ix_devices_ip_address'), 'devices', ['ip_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_ip_address'), table_name='devices')
    op.drop_index(op.f('ix_device_events_time'), table_name='device_events')
    op.drop_index(op.f('ix_device_events_device_id'), table_name='device_events')
    op.drop_column('device_events', 'id')
    # ### end Alembic commands ###
