"""add_ip_address_to_devices

Revision ID: b9fad77027de
Revises: 602f3a877b70
Create Date: 2026-03-14 16:22:23.778336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9fad77027de'
down_revision: Union[str, None] = '602f3a877b70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.drop_constraint('devices_matter_node_id_key', 'devices', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('devices_matter_node_id_key', 'devices', ['matter_node_id'])
    op.drop_column('devices', 'ip_address')
    # ### end Alembic commands ###
